AllCops:
  Excludes:
    - log/**
    - vendor/**/*
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
    - Rakefile
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Rails:
  Enabled: true

Documentation:
  Enabled: false
