import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :setlistify, SetlistifyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: System.get_env("PORT") || 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "qNJ7lJLK3GcEuONMenwia0XD4sw3J9l2hcJcxQQA6JlF+wNmowANvZ9TtNx25ESU",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:setlistify, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :setlistify, SetlistifyWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/setlistify_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :setlistify, dev_routes: true

# Logger configuration with Loki backend
config :logger,
  backends: [:console, Setlistify.LokiLogger],
  level: :debug

# Console logger configuration - include trace context
config :logger, :console,
  format: "$time [$level] $message $metadata\n",
  metadata: [:request_id, :trace_id, :span_id, :user_id, :module, :function]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view, debug_heex_annotations: true

# OpenTelemetry configuration
# NOTE: This is overridden by runtime.exs if GRAFANA_CLOUD_API_KEY is set
# Keeping minimal config here for local development fallback

# Loki logger backend configuration
config :logger, Setlistify.LokiLogger,
  url: "http://localhost:3100/loki/api/v1/push",
  level: :info,
  metadata: [:request_id, :trace_id, :span_id, :user_id],
  max_buffer: 50,
  labels: %{
    "application" => "setlistify",
    "environment" => "development"
  }
